### ISSUE TITLE
Actividad 6 - Trabajo en Equipo

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-4as_coders#1]
[Actividad 6 - Equipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-4as_coders/files/14705087/Actividad.6.-.Equipo.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 17, el nombre del docente esta mal.
Hizo falta solo explicar en si como se realizo tu empaquetado

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
